package demo.examples;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BlogPost implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public BlogPost() {
    }

}