package demo.examples;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Comment implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String body;

   public Comment()
   {
   }

   public java.lang.String getBody()
   {
      return this.body;
   }

   public void setBody(java.lang.String body)
   {
      this.body = body;
   }

   public Comment(java.lang.String body)
   {
      this.body = body;
   }

}