package demo.examples;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ContentValidationResult implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean bad;
   private java.lang.Integer badWordsCount;

   public ContentValidationResult()
   {
   }

   public java.lang.Boolean getBad()
   {
      return this.bad;
   }

   public void setBad(java.lang.Boolean bad)
   {
      this.bad = bad;
   }

   public java.lang.Integer getBadWordsCount()
   {
      return this.badWordsCount;
   }

   public void setBadWordsCount(java.lang.Integer badWordsCount)
   {
      this.badWordsCount = badWordsCount;
   }

   public ContentValidationResult(java.lang.Boolean bad,
         java.lang.Integer badWordsCount)
   {
      this.bad = bad;
      this.badWordsCount = badWordsCount;
   }

}