package demo.examples;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Content implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String content;

   public Content()
   {
   }

   public java.lang.String getContent()
   {
      return this.content;
   }

   public void setContent(java.lang.String content)
   {
      this.content = content;
   }

   public Content(java.lang.String content)
   {
      this.content = content;
   }

}