package demo.examples;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ContentValidationResult implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean is-bad;

   public ContentValidationResult()
   {
   }

   public java.lang.Boolean getIsbad()
   {
      return this.isbad;
   }

   public void setIsbad(java.lang.Boolean isbad)
   {
      this.isbad = isbad;
   }

   public ContentValidationResult(java.lang.Boolean isbad)
   {
      this.isbad = isbad;
   }

}