package demo.examples;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Email implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String email;

   public Email()
   {
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public Email(java.lang.String email)
   {
      this.email = email;
   }

}