package demo.examples;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PullRequest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String title;
   private java.lang.Integer number;
   private java.lang.String state;

   public PullRequest()
   {
   }

   public java.lang.String getTitle()
   {
      return this.title;
   }

   public void setTitle(java.lang.String title)
   {
      this.title = title;
   }

   public java.lang.Integer getNumber()
   {
      return this.number;
   }

   public void setNumber(java.lang.Integer number)
   {
      this.number = number;
   }

   public java.lang.String getState()
   {
      return this.state;
   }

   public void setState(java.lang.String state)
   {
      this.state = state;
   }

   public PullRequest(java.lang.String title, java.lang.Integer number,
         java.lang.String state)
   {
      this.title = title;
      this.number = number;
      this.state = state;
   }

}