package demo.examples;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class VacationRequest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer length;
   private java.lang.String reason;
   private java.lang.Boolean unpaid;

   public VacationRequest()
   {
   }

   public java.lang.Integer getLength()
   {
      return this.length;
   }

   public void setLength(java.lang.Integer length)
   {
      this.length = length;
   }

   public java.lang.String getReason()
   {
      return this.reason;
   }

   public void setReason(java.lang.String reason)
   {
      this.reason = reason;
   }

   public java.lang.Boolean getUnpaid()
   {
      return this.unpaid;
   }

   public void setUnpaid(java.lang.Boolean unpaid)
   {
      this.unpaid = unpaid;
   }

   public VacationRequest(java.lang.Integer length, java.lang.String reason,
         java.lang.Boolean unpaid)
   {
      this.length = length;
      this.reason = reason;
      this.unpaid = unpaid;
   }

}